name: daisy
description: A comic reader.

publish_to: 'none'

version: 0.1.24+1


environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  rust_lib_daisy:
    path: rust_builder
  flutter_rust_bridge: 2.4.0
  another_xlider: ^1.0.1+2
  modal_bottom_sheet: ^3.0.0-pre
  photo_view: ^0.15.0
  scrollable_positioned_list: ^0.2.3
  permission_handler: ^11.3.1
  flutter_styled_toast: ^2.2.1
  flutter_svg: ^1.0.3
  flutter_colorpicker: ^1.0.3
  crypto: ^3.0.2
  ffi: 2.0.1
  flutter_html: ^3.0.0-beta.2
  awesome_select: ^6.0.0
  url_launcher: ^6.3.0
  uuid: ^4.5.1
  date_format: ^2.0.9
  event: ^3.1.0
  app_links: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
